name: Build and deploy Node.js app to Azure Web App - exotic-world-server

on:
  push:
    branches:
      - deploy-azure
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: npm install
        working-directory: server

      - name: Build app (optional)
        run: npm run build --if-present
        working-directory: server

      - name: Run tests (optional)
        run: npm run test --if-present
        working-directory: server

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: server

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_81F12D0001374865AFC8E4CE50704C7F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_4E8CB3BB193A4DDFABFD1E16B57847FD }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7131727DC5664AEF86419C6D528D2412 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'exotic-world-server'
          slot-name: 'Production'
          package: .
